# 1. build functions with numpy

In [1]:
import numpy as np
import math

sigmoid with single number

In [2]:
def basic_sigmoid(x):
  s = 1 / (1 + math.exp(-x))
  return s

In [3]:
basic_sigmoid(3)

0.9525741268224334

sigmoid with numpy

In [4]:
x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [5]:
def sigmoid(x):
  s = 1 / (np.exp(-x) + 1)
  return s

In [6]:
x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

sigmoid gradient

In [7]:
def sigmoid_derivative(x):
  """
  Compute the gradient of sigmoid function
  
  Arguments :
    x - scalar or numpy array

  Return :
    ds - computed gradient of sigmoid   
  
  """
  s = sigmoid(x)
  ds = s * (1-s)
  return ds

In [8]:
x = np.array([1,2,3])
print('sigmoid_defirative(x) = ' + str(sigmoid_derivative(x)))

sigmoid_defirative(x) = [0.19661193 0.10499359 0.04517666]


reshaping array

In [9]:
def image2vector(image):
  """
  change the shape of image type array to vector array

  Argument :
    image - numpy array of shape(length, height, depth)
  
  Returns : 
    v - a vector of shape(length * height * depth, 1)
  """
  v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
  return v

In [10]:
image = np.random.rand(3,2,3)
print(f"image shape : {image.shape}")
print(f"image : \n{image}")
print(f"reshaped_image : \n{image2vector(image)}")

image shape : (3, 2, 3)
image : 
[[[0.52582621 0.19206954 0.48587953]
  [0.13411522 0.80696266 0.91596616]]

 [[0.47538844 0.20985127 0.63302372]
  [0.97377864 0.68299025 0.545655  ]]

 [[0.91122981 0.60929453 0.64899236]
  [0.03147374 0.50364423 0.31251683]]]
reshaped_image : 
[[0.52582621]
 [0.19206954]
 [0.48587953]
 [0.13411522]
 [0.80696266]
 [0.91596616]
 [0.47538844]
 [0.20985127]
 [0.63302372]
 [0.97377864]
 [0.68299025]
 [0.545655  ]
 [0.91122981]
 [0.60929453]
 [0.64899236]
 [0.03147374]
 [0.50364423]
 [0.31251683]]


normalizing rows

In [11]:
def normalizeRows(x):
  """
  Implement a funciton that normalizes each row of th ematrix x
  Argument:
  x - numpy matrix of shape(n, m)

  Returns : 
  y - The normalized (by row) numpy matrix.
  """
  x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
  x = x/ x_norm
  return x


In [12]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


softmax functions

In [13]:
def softmax(x):
  """
  Calculate the softamx for each row of the input x
  Argument 
    x - A numpy matrix of shape (m, n)
  Returns :
    s - A numpy matrix of softmax of x, shape (m, n)
  """
  x_exp = np.exp(x)
  x_sum = np.sum(x_exp, axis = 1, keepdims = True)
  s = x_exp / x_sum
  return s

In [14]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


# 2 - Vectorization


vectorization help to recude time, and parallel computing with cpu

In [15]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

#Classical dot product of vectors
tic = time.process_time()
dot = 0
for i in range(len(x1)):
  dot+= x1[i] * x2[i]
toc = time.process_time()
print(f"dot = {dot} \n ------- Computation time =  {1000 * (toc-tic)} ms")

#Classical outer product implementation
tic = time.process_time()
outer = np.zeros((len(x1), len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    outer[i, j] = x1[i] * x2[j]
toc = time.process_time()
print(f"outer = {outer} \n ------- Computation time = {1000*(toc - tic)} ms")

#Classical Elementwise implemetation
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
  mul[i] = x1[i] * x2[i]
toc = time.process_time()
print(f"elementwise multiplication = {mul} \n ------ computation time = {1000*(toc - tic)} ms")

#classic general dot product
W = np.random.rand(3, len(x1))
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
  for j in range(len(x1)):
    gdot[i] += W[i, j] * x1[j]
toc = time.process_time()
print(f"gdot =  {gdot} \n ------- Computation time = {1000*(toc - tic)} ms")





dot = 278 
 ------- Computation time =  0.11250399999984673 ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

In [18]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.11243499999968876ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.1281930000001097ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.054753000000129504ms
gdot = [21.16187892 24.80270084 21.745352

## 2.1 Implement the L1 and L2 loss function

In [25]:
def L1(yhat, y):
  """
  Arguments : 
  yhat -- vector of sizie m (predicted labels)
  y -- vector of size m (true labels)

  Returns:
  loss - the value of the L1 loss
  """
  loss = sum(abs(yhat-y))
  return loss

In [35]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [37]:
def L2(yhat, y):
  """
  Arguments:
  yhat - vector of size m(predicted labels)
  y - vector of size m(true labels)

  Returns:
  loss - the value of th eL2 loss function defined above
  """
  x = yhat - y
  loss = np.dot(x, x)

  return loss


In [38]:
yhat = np.array([.9, .2, .1, .4, .9])
y = np.array([1, 0, 0, 1,1])
print(f"L2 = {L2(yhat, y)}")

L2 = 0.43
